output_folder: /root/licas3/benchmark/reports/h
models:
  variables:
    num_frames_in_seq: [1, 10, 20]
  # TODO(future users): below are only a demo usage. PLEASE UPDATE them to where you save the pbs
  kitti:
    id_h001:
      model_fp: /root/licas3/inference/h/licas3_kitti_sample_01_stride_05_beam_64_downsample@1617680382.8551874/best.pb
      l: 5
      s: 1
    id_h101:
      model_fp: /root/sl/inference/h/licas3_kitti_sample_01_stride_05_beam_64_downsample@1618699432.489519/best.pb
      l: 5
      s: 1
  newer_college_psudo_gt:
    id_h011:
      model_fp: /root/licas3/inference/h/licas3_kitti_sample_05_stride_05_beam_64_downsample@1617578670.0181055/best.pb
      l: 5
      s: 5
    id_h111:
      model_fp: /root/sl/inference/h/licas3_kitti_sample_05_stride_05_beam_64_downsample@1618699882.8105345/best.pb
      l: 5
      s: 5
  newer_college_gt:
    id_h211:
      model_fp: /root/licas3/inference/h/licas3_newer_college_sample_01_stride_05_beam_64_downsample@1618179724.060939/best.pb
      l: 5
      s: 1
